;/*FB_PKG_DELIM*/

__d("CometGroupDiscussionRootSuccessQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="23882178544739210"}),null);
__d("CometGroupRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="29170457372597587"}),null);
__d("CometGroupRootQuery$Parameters",["CometGroupRootQuery_facebookRelayOperation","GroupsCometGroupChatLazyLoadLastMessageSnippet.relayprovider"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometGroupRootQuery_facebookRelayOperation"),metadata:{},name:"CometGroupRootQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__GroupsCometGroupChatLazyLoadLastMessageSnippetrelayprovider:b("GroupsCometGroupChatLazyLoadLastMessageSnippet.relayprovider")}}};e.exports=a}),null);
__d("CometVideoHomeLOEExploreLeftRailSectionQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5964852866867127"}),null);
__d("CometVideoHomeLOEExploreLeftRailSectionQuery$Parameters",["CometVideoHomeLOEExploreLeftRailSectionQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometVideoHomeLOEExploreLeftRailSectionQuery_facebookRelayOperation"),metadata:{},name:"CometVideoHomeLOEExploreLeftRailSectionQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometVideoHomeRootProviderQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8099333720109156"}),null);
__d("CometVideoHomeRootProviderQuery$Parameters",["CometVideoHomeRootProviderQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometVideoHomeRootProviderQuery_facebookRelayOperation"),metadata:{},name:"CometVideoHomeRootProviderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("createContentAreaCompoundEntryPointBuilder",["createGenericCompoundEntryPointBuilder"],(function(a,b,c,d,e,f,g){"use strict";function a(a,b){var d=c("createGenericCompoundEntryPointBuilder")(a,b);return function(a,b){var c={getPreloadProps:b,root:a};return d(function(a){return{contentEntryPoint:{entryPoint:c,entryPointParams:a}}})}}g["default"]=a}),98);
__d("buildCometVideoHomeRouteForResource.entrypoint",["CometVideoHomeLOEExploreLeftRailSectionQuery$Parameters","CometVideoHomeRootProviderQuery$Parameters","createContentAreaCompoundEntryPointBuilder"],(function(a,b,c,d,e,f,g){"use strict";function a(a){return c("createContentAreaCompoundEntryPointBuilder")(a,function(a){return{exploreQueryReference:{parameters:b("CometVideoHomeLOEExploreLeftRailSectionQuery$Parameters"),variables:{}},rootProviderQueryReference:{parameters:b("CometVideoHomeRootProviderQuery$Parameters"),variables:{}}}})}g["default"]=a}),98);
__d("buildCometVideoHomeRoute.entrypoint",["JSResourceForInteraction","buildCometVideoHomeRouteForResource.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometVideoHomeRouteForResource.entrypoint")(c("JSResourceForInteraction")("CometVideoHomeRoot.react").__setRef("buildCometVideoHomeRoute.entrypoint"));g["default"]=a}),98);
__d("CometVideoHomeFeedRoot.entrypoint",["CometVideoHomeFeedEntryPointVariables","CometVideoHomeFeedRootQuery$Parameters","CometVideoHomeSurfaceHighlightsWrapperQuery$Parameters","JSResourceForInteraction","buildCometVideoHomeRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometVideoHomeRoute.entrypoint")(c("JSResourceForInteraction")("CometVideoHomeFeedRoot.react").__setRef("CometVideoHomeFeedRoot.entrypoint"),function(a){return{queries:{feedRootQueryReference:{environmentProviderOptions:{preloaderGroup:"video_home"},options:{fetchPolicy:"network-only"},parameters:b("CometVideoHomeFeedRootQuery$Parameters"),variables:c("CometVideoHomeFeedEntryPointVariables")},surfaceHighlightsQueryReference:{parameters:b("CometVideoHomeSurfaceHighlightsWrapperQuery$Parameters"),variables:{}}}}});g["default"]=a}),98);
__d("CometVideoHomeHashtagRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9867916263238717"}),null);
__d("CometVideoHomeHashtagRootQuery$Parameters",["CometVideoHomeHashtagRootQuery_facebookRelayOperation","FBReelsIFUTileContent_reelsIFUPlayOnHover.relayprovider"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometVideoHomeHashtagRootQuery_facebookRelayOperation"),metadata:{},name:"CometVideoHomeHashtagRootQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__FBReelsIFUTileContent_reelsIFUPlayOnHoverrelayprovider:b("FBReelsIFUTileContent_reelsIFUPlayOnHover.relayprovider")}}};e.exports=a}),null);
__d("CometVideoHomeHashtagRoot.entrypoint",["CometVideoHomeHashtagRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometVideoHomeRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometVideoHomeRoute.entrypoint")(c("JSResourceForInteraction")("CometVideoHomeHashtagRoot.react").__setRef("CometVideoHomeHashtagRoot.entrypoint"),function(a){a={hashtag:a.routeProps.id};return{queries:{queryReference:{parameters:b("CometVideoHomeHashtagRootQuery$Parameters"),variables:{scale:d("WebPixelRatio").get(),triggerData:a}}}}});g["default"]=a}),98);
__d("GroupFeedType.facebook",["$InternalEnum"],(function(a,b,c,d,e,f){a=b("$InternalEnum").Mirrored(["ANONYMOUS_POST","BUY_AND_SELL","BUY_AND_SELL_DISCUSSION","BUY_AND_SELL_MANAGE_LISTINGS","DISCUSSION","MEDIA","PHOTO","QUESTIONS","SUBGROUP","VIDEO","WORK_GARDEN"]);c=a;f["default"]=c}),66);
__d("GroupsCometDiscussionLayoutRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9665420013503669"}),null);
__d("GroupsCometLazyLoadFeaturedSection.relayprovider",[],(function(a,b,c,d,e,f){"use strict";a={get:function(){return!1}};f["default"]=a}),66);
__d("buildGroupCometRootRoute.entrypoint",["CometGroupRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","createContentAreaCompoundEntryPointBuilder"],(function(a,b,c,d,e,f,g){"use strict";a=c("createContentAreaCompoundEntryPointBuilder")(c("JSResourceForInteraction")("CometGroupRoot.react").__setRef("buildGroupCometRootRoute.entrypoint"),function(a){var c=a.routeParams;a=a.routeProps;var e=a.groupID;a=a.section;return{rootQueryReference:{options:{fetchPolicy:"network-only"},parameters:b("CometGroupRootQuery$Parameters"),variables:{currentSection:a,groupID:e,inviteShortLinkKey:c==null?void 0:c.invite_short_link_key,isChainingRecommendationUnit:(c==null?void 0:c.action_source)==="group_mall_recommendation_affordance",scale:d("WebPixelRatio").get()}}}});g["default"]=a}),98);