;/*FB_PKG_DELIM*/

__d("CometUFIGroupMentionsComposerPluginInner.react",["react","react-compiler-runtime","useDeferredModuleOnReady"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){var b=d("react-compiler-runtime").c(4),e=a.pluginProps,f=a.config;a=a.upgradedPluginDeferred_FOR_DRAFTJS_AND_OUTLINE;a=c("useDeferredModuleOnReady")(a);if(a==null)return null;else{var g;b[0]!==a||b[1]!==f||b[2]!==e?(g=i.jsx(a,{config:f,pluginProps:e}),b[0]=a,b[1]=f,b[2]=e,b[3]=g):g=b[3];return g}}g["default"]=a}),98);
__d("CometVideoHomeFunnelLoggingContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext({hasPermalinkInjection:!1});g["default"]=b}),98);
__d("FDSMagnifyingGlassFilled20Icon",["cr:15242"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15242")}),98);
__d("FDSMagnifyingGlassFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("491283"),20);b=a;g["default"]=b}),98);
__d("GroupsCometMemberProfileLink_group.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"GroupsCometMemberProfileLink_group",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],type:"Group",abstractKey:null};e.exports=a}),null);
__d("GroupsCometMemberProfileLink.react",["ActorHovercard.react","CometLink.react","CometPressable.react","CometRelay","FDSHovercardGroupContext","GroupsCometMemberProfileLink_group.graphql","ProfileCometContextualProfileGating","XCometContextualProfileControllerRouteBuilder","mergeRefs","react","react-compiler-runtime","stylex"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j,k=j||(j=d("react"));j.useMemo;function a(a){var e=d("react-compiler-runtime").c(26),f=a.color,g=a.group$key,j=a.groupID,m=a.kind,n=a.memberID,o=a.xstyle,p=m===void 0?"link":m;d("CometRelay").useFragment(h!==void 0?h:h=b("GroupsCometMemberProfileLink_group.graphql"),g);m=l(a);var q=m.linkProps,r=m.ref;e[0]!==j?(g={groupID:j},e[0]=j,e[1]=g):g=e[1];m=g;j=m;g=a["aria-hidden"];m=a["aria-label"];var s;e[2]!==a.children||e[3]!==a.focusable||e[4]!==g||e[5]!==m?(s={"aria-hidden":g,"aria-label":m,children:a.children,focusable:a.focusable},e[2]=a.children,e[3]=a.focusable,e[4]=g,e[5]=m,e[6]=s):s=e[6];var t=s;e[7]!==o?(g=(i||(i=c("stylex")))(o),e[7]=o,e[8]=g):g=e[8];m=a["aria-hidden"]===!0?!0:void 0;s=a["aria-label"];e[9]!==f||e[10]!==p||e[11]!==q||e[12]!==t||e[13]!==r?(o=function(a){a=c("mergeRefs")(a,r);switch(p){case"link":return k.jsx(c("CometLink.react"),babelHelpers["extends"]({},t,{color_DEPRECATED:f,href:q.href,ref:a}));case"profilePhoto":return k.jsx(c("CometPressable.react"),babelHelpers["extends"]({},t,{linkProps:{url:q.href},overlayRadius:"50%",ref:a}));default:return p}},e[9]=f,e[10]=p,e[11]=q,e[12]=t,e[13]=r,e[14]=o):o=e[14];e[15]!==n||e[16]!==m||e[17]!==s||e[18]!==o?(a=k.jsx(c("ActorHovercard.react"),{actorID:n,"aria-hidden":m,"aria-label":s,display:"inline",children:o}),e[15]=n,e[16]=m,e[17]=s,e[18]=o,e[19]=a):a=e[19];e[20]!==j||e[21]!==a?(n=k.jsx(c("FDSHovercardGroupContext").Provider,{value:j,children:a}),e[20]=j,e[21]=a,e[22]=n):n=e[22];e[23]!==n||e[24]!==g?(m=k.jsx("span",{className:g,children:n}),e[23]=n,e[24]=g,e[25]=m):m=e[25];return m}function l(a){var b=d("react-compiler-runtime").c(9),e=a.groupID,f=a.hasMemberProfile,g=a.memberID,h=a.onClick;a=a.profileUrl;if(d("ProfileCometContextualProfileGating").canViewCometContextualProfile()&&f){b[0]!==e||b[1]!==g?(f=c("XCometContextualProfileControllerRouteBuilder").buildURL({group_idorvanity:e,member_id:g}),b[0]=e,b[1]=g,b[2]=f):f=b[2];b[3]!==h||b[4]!==f?(e={linkProps:{href:f,onClick:h}},b[3]=h,b[4]=f,b[5]=e):e=b[5];return e}b[6]!==h||b[7]!==a?(g={linkProps:{href:a,onClick:h}},b[6]=h,b[7]=a,b[8]=g):g=b[8];return g}g["default"]=a}),98);
__d("cometUFIComposerGroupMentionsPlugin_plugin.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"cometUFIComposerGroupMentionsPlugin_plugin",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],type:"CommentComposerGroupMentionsPlugin",abstractKey:null};e.exports=a}),null);
__d("cometUFIComposerGroupMentionsPlugin_pluginData.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"InlineDataFragment",name:"cometUFIComposerGroupMentionsPlugin_pluginData"};e.exports=a}),null);
__d("cometUFIComposerGroupMentionsPlugin",["CometRelay","CometUFIGroupMentionsComposerPluginInner.react","FBLogger","cometUFIComposerGroupMentionsPlugin_plugin.graphql","cometUFIComposerGroupMentionsPlugin_pluginData.graphql","requireDeferred"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=c("requireDeferred")("createUpgradedUFI2GroupMentionsComposerPluginForLexical").__setRef("cometUFIComposerGroupMentionsPlugin");h!==void 0?h:h=b("cometUFIComposerGroupMentionsPlugin_plugin.graphql");function a(a){a=a.fragmentKey;a=d("CometRelay").readInlineData(i!==void 0?i:i=b("cometUFIComposerGroupMentionsPlugin_pluginData.graphql"),a);var e=a.group_id;a=a.post_id;if(e==null||a==null)throw c("FBLogger")("ufight_club").mustfixThrow("This plugin cannot be rendered without group_id or post_id");e={contextID:null,groupID:e,postID:a,upgradedPluginDeferred_FOR_DRAFTJS_AND_OUTLINE:j};a=e.upgradedPluginDeferred_FOR_DRAFTJS_AND_OUTLINE;e=babelHelpers.objectWithoutPropertiesLoose(e,["upgradedPluginDeferred_FOR_DRAFTJS_AND_OUTLINE"]);return{above:null,action:null,below:c("CometUFIGroupMentionsComposerPluginInner.react"),id:"group_mentions",inside:null,props:{config:e,upgradedPluginDeferred_FOR_DRAFTJS_AND_OUTLINE:a}}}g["default"]=a}),98);
__d("cometUFIComposerGroupMentionsPlugin_plugin$normalization.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"SplitOperation",metadata:{},name:"cometUFIComposerGroupMentionsPlugin_plugin$normalization",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}]};e.exports=a}),null);